//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch ECTImportX.rc
//
#define IDS_ECTIMPORTX                  1
#define IDD_ABOUTBOX_ECTIMPORTX         1
#define IDB_ECTIMPORTX                  1
#define IDI_ABOUTDLL                    1
#define IDS_ECTIMPORTX_PPG              2
#define IDS_OPENFILEFILTER              3
#define IDOK2                           3
#define IDS_OPENFILEDEFEXT              4
#define IDS_CONFIRMDELIMPORTDESCR       5
#define IDS_NAMEISEMPTY                 6
#define IDS_NAMEALREADYEXISTS           7
#define IDS_IMPERR_INVALIDPARAMS        8
#define IDS_IMPERR_EOFINHEADER          9
#define IDS_IMPERR_UNKNOWN              10
#define IDS_STANDARD                    11
#define IDS_FIELDX                      12
#define IDS_DATATYPE_UNKNOWN            13
#define IDS_DATATYPE_DATE               14
#define IDS_DATATYPE_TEXT               15
#define ID_ABOUTBOX                     0x0010
#define IDS_DATATYPE_CURRENCY           16
#define IDS_DATATYPE_EA                 17
#define IDS_DATATYPE_INT                18
#define IDS_VERSION                     19
#define IDS_APP_ABOUT                   20
#define IDS_PLUGIN_MENUENTRY            21
#define IDS_PLUGIN_VERSIONERROR         22
#define IDS_IMPORTSUCCESFUL             23
#define IDS_PARAMERR_NOFILENAME         24
#define IDS_PARAMERR_NOFSEPARATORCHAR   25
#define IDS_PARAMERR_NOFIELDEA          26
#define IDS_PARAMERR_NOFIELDBETRAG      27
#define IDS_PARAMETER_SEPARATORCHAR_TO_LONG 28
#define IDS_NO_IMPORTDESCR_SELECTED     29
#define IDS_IMPERR_INVALID_FIELD_INDEX  30
#define IDS_IMPERR_CONVERSION_FALIED    31
#define IDS_IMPERR_FILE_EMPTY           32
#define IDS_IMPERR_LINE_EMPTY           33
#define IDS_IMPORTSTATUS_ERRORLIST_COL1 34
#define IDS_IMPORTSTATUS_ERRORLIST_COL2 35
#define IDS_DEFAULTNAME                 36
#define IDS_ERROR_SAVETOINIFILE         37
#define IDS_ERROR_LOADFROMINIFILE       38
#define IDS_CONVERSIONRULE_INCOME_ONLY  39
#define IDS_CONVERSIONRULE_EXPENSE_ONLY 40
#define IDS_CONVERSIONRULE_USE_SIGN     41
#define IDS_IMPERR_INVALID_PARAMETERS   42
#define IDS_OPENGAWKFILTER              43
#define IDS_OPENGAWKDEFEXT              44
#define IDS_PROGRESS_CAPTION            48
#define IDS_PROGRESS_STATUS_IMPORTING   49
#define IDS_CONFIRM_USERINTERRUPT_MESSAGE 50
#define IDS_CONFIRM_USERINTERRUPT_CAPTION 51
#define IDS_DATATYPE_BRUTTONETTO        52
#define IDS_EMAIL                       53
#define IDS_CONVERSIONRULE_BRUTTO_ONLY  54
#define IDS_CONVERSIONRULE_NETTO_ONLY   55
#define IDS_PROGRESS_STATUS_SORTING     56
#define IDS_ECTIMPORTX_PPG_CAPTION      200
#define IDD_IMPORTFORM                  202
#define CG_IDD_PROGRESS                 203
#define IDD_IMPORTDESCR                 204
#define IDD_IMPORTSTATUS                206
#define IDD_NEWIMPORTDESCR              207
#define IDC_DOKUMENTCTRL1               209
#define IDC_BUCHUNGCTRL1                210
#define IDC_STATIC30                    211
#define IDC_EINSTELLUNGCTRL1            212
#define IDC_BUTTON1                     213
#define IDC_INFO                        213
#define IDC_STATIC35                    214
#define IDC_NEWIMPORTDESCR              1001
#define IDC_DELIMPORTDESCR              1002
#define IDC_FILENAME                    1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_GAWKSCRIPT                  1004
#define IDC_SELFILENAME                 1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_FILECONTENT                 1006
#define IDC_NUMHEADERLINES              1007
#define IDC_SELGAWKSCRIPT               1008
#define IDC_EXEGAWKSCRIPT               1009
#define IDC_SEPARATORCHAR               1010
#define IDC_NAME                        1010
#define IDC_IMPORTDESCR                 1011
#define IDC_STATIC1                     1012
#define IDC_STATIC2                     1013
#define IDC_STATIC3                     1014
#define IDC_STATIC31                    1015
#define IDC_STATIC4                     1016
#define IDC_GROUPBOX1                   1017
#define IDC_VIEWFILECONTENT             1018
#define IDC_EDITGAWKSCRIPT              1019
#define IDC_STATIC32                    1020
#define IDC_STATIC9                     1021
#define IDC_FIELD_EA                    1022
#define IDC_STATIC10                    1023
#define IDC_NUMHEADERLINES_SPIN         1024
#define IDC_FIELD_KONTO                 1025
#define IDC_FIELD_DATUM                 1026
#define IDC_FIELD_BESCHREIBUNG          1027
#define IDC_FIELD_BETRAG                1028
#define IDC_FIELD_STEUERSATZ            1029
#define IDC_GROUPBOX2                   1030
#define IDC_STATIC5                     1031
#define IDC_STATIC6                     1032
#define IDC_STATIC7                     1033
#define IDC_STATIC8                     1034
#define IDC_FIELD_DATUM_FORMAT          1035
#define IDC_EMAIL                       1036
#define IDC_FIELD_BETRAG_FORMAT         1036
#define IDC_FIELD_STEUERSATZ_FORMAT     1037
#define IDC_FIELD_EA_FORMAT_E           1038
#define IDC_FIELD_EA_FORMAT_A           1039
#define IDC_STATIC11                    1040
#define IDC_STATIC12                    1041
#define IDC_STATIC13                    1042
#define IDC_STATIC14                    1043
#define IDC_STATIC15                    1044
#define IDC_STATIC16                    1045
#define IDC_FIELD_DATUM_DELIMITER       1046
#define IDC_FIELD_AFAAKTJAHR            1047
#define IDC_VERSION                     1048
#define IDC_STATIC17                    1048
#define IDC_FIELD_AFADAUER              1049
#define IDC_STATIC18                    1050
#define IDC_MESSAGES                    1050
#define IDC_FIELD_BRUTTONETTO           1051
#define IDC_STATIC19                    1052
#define IDC_ERRORICON                   1052
#define IDC_ABOUTICON                   1053
#define IDC_STATIC20                    1053
#define IDC_FIELD_BN_FORMAT_BRUTTO      1054
#define IDC_STATIC21                    1055
#define IDC_FIELD_BN_FORMAT_NETTO       1056
#define IDC_FIELD_BELEGNUMMER           1057
#define IDC_STATIC22                    1058
#define IDC_STATIC25                    1059
#define IDC_FIELD_AFARESTWERT_FORMAT    1060
#define IDC_FIELD_AFADEGSATZ            1061
#define IDC_STATIC23                    1062
#define IDC_FIELD_AFARESTWERT           1063
#define IDC_STATIC24                    1064
#define IDC_STATIC26                    1065
#define IDC_FIELD_AFADEGSATZ_FORMAT     1066
#define IDC_VIEWFILECONTENT2            1067
#define IDC_UTF8CONVERT                 1067
#define IDC_STATIC27                    1068
#define IDC_FIELD_AFAGENAUIGKEIT        1069
#define IDC_STATIC28                    1070
#define IDC_FIELD_BETRIEB               1071
#define IDC_STATIC29                    1072
#define IDC_FIELD_BESTANDSKONTO         1073
#define IDC_COPYEXISTING                1074

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         215
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
